import { Recipe } from "./mockData";


export const allRecipes: Recipe[] = [

    {
        id: 'rec-2',
        title: 'Grilled Chicken',
        image: 'https://www.fakefoodfree.com/wp-content/uploads/2017/06/IMG_9501-680x1020.jpg',
        cookingTime: 45,
        prepTime: 15,
        bakingTime: 25,
        restingTime: 5,
        difficulty: 'Medium',
        servings: 2,
        type: 'non-veg',
        mealType: ['lunch', 'dinner'],
        ingredients: ['Chicken', 'Yogurt', 'Lemon', 'Garlic', 'Ginger', 'Red Chili', 'Turmeric', 'Cumin'],
        ingredientsWithQuantities: [
            { name: 'Chicken', amount: 500, unit: 'g' },
            { name: 'Yogurt', amount: 1, unit: 'cup' },
            { name: 'Lemon', amount: 1, unit: '' },
            { name: 'Garlic', amount: 1, unit: 'tbsp' },
            { name: 'Ginger', amount: 1, unit: 'tbsp' },
            { name: 'Red Chili', amount: 1, unit: 'tsp' },
            { name: 'Turmeric', amount: 0.5, unit: 'tsp' },
            { name: 'Cumin', amount: 1, unit: 'tsp' }
        ],
        instructions: [
            'Mix yogurt with spices, ginger, garlic, and lemon juice',
            'Marinate chicken pieces for at least 2 hours',
            'Preheat grill to medium-high heat',
            'Grill chicken for 15-20 minutes until internal temp reaches 165°F',
            'Let rest for 5 minutes before serving',
            'Serve with salad and dip'
        ],
        utensils: ['Grill pan', 'Mixing bowl', 'Tongs'],
        nutrition: { calories: 280, protein: 38, carbs: 5, fat: 12 }
    },
    {
        id: 'rec-3',
        title: 'Creamy Pasta Alfredo',
        image: 'https://images.unsplash.com/photo-1609166639722-47053ca112ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMGl0YWxpYW4lMjBmb29kfGVufDF8fHx8MTc3MTU0MTEwMnww&ixlib=rb-4.1.0&q=80&w=1080',
        cookingTime: 25,
        prepTime: 10,
        bakingTime: 15,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 2,
        type: 'veg',
        mealType: ['dinner'],
        ingredients: ['Pasta', 'Butter', 'Cheese', 'Milk', 'Garlic', 'Bell Pepper'],
        ingredientsWithQuantities: [
            { name: 'Pasta', amount: 200, unit: 'g' },
            { name: 'Butter', amount: 50, unit: 'g' },
            { name: 'Cheese', amount: 100, unit: 'g' },
            { name: 'Milk', amount: 200, unit: 'ml' },
            { name: 'Garlic', amount: 2, unit: 'cloves' },
            { name: 'Bell Pepper', amount: 1, unit: '' }
        ],
        instructions: [
            'Cook pasta according to package directions',
            'In a pan, melt butter and sauté minced garlic',
            'Add milk, bring to a simmer, then stir in grated cheese until melted',
            'Toss cooked pasta and sautéed bell peppers in the sauce',
            'Season with salt and pepper',
            'Garnish with parsley and serve hot'
        ],
        utensils: ['Large pot', 'Sauté pan', 'Cheese grater'],
        nutrition: { calories: 450, protein: 15, carbs: 52, fat: 20 }
    },
    {
        id: 'rec-4',
        title: 'Fresh Garden Salad',
        image: 'https://images.unsplash.com/photo-1620019989479-d52fcedd99fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMHNhbGFkJTIwYm93bHxlbnwxfHx8fDE3NzE1NjkwMTN8MA&ixlib=rb-4.1.0&q=80&w=1080',
        cookingTime: 10,
        prepTime: 10,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 1,
        type: 'veg',
        mealType: ['lunch', 'snack'],
        ingredients: ['Tomato', 'Carrot', 'Bell Pepper', 'Onion', 'Lemon'],
        ingredientsWithQuantities: [
            { name: 'Tomato', amount: 2, unit: '' },
            { name: 'Carrot', amount: 1, unit: '' },
            { name: 'Bell Pepper', amount: 1, unit: '' },
            { name: 'Onion', amount: 0.5, unit: '' },
            { name: 'Lemon', amount: 0.5, unit: '' }
        ],
        instructions: [
            'Chop all vegetables into bite-size pieces',
            'Mix vegetables in a large bowl',
            'Squeeze fresh lemon juice over the salad',
            'Add salt and pepper to taste',
            'Toss well to combine',
            'Serve immediately'
        ],
        utensils: ['Knife', 'Cutting board', 'Large bowl'],
        nutrition: { calories: 85, protein: 3, carbs: 18, fat: 1 }
    },
    {
        id: 'rec-5',
        title: 'Chicken Biryani',
        image: 'https://images.unsplash.com/photo-1666190092689-e3968aa0c32c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiaXJ5YW5pJTIwcmljZSUyMGRpc2h8ZW58MXx8fHwxNzcxNDgwODk0fDA&ixlib=rb-4.1.0&q=80&w=1080',
        cookingTime: 60,
        prepTime: 20,
        bakingTime: 35,
        restingTime: 5,
        difficulty: 'Hard',
        servings: 4,
        type: 'non-veg',
        mealType: ['lunch', 'dinner'],
        ingredients: ['Chicken', 'Rice', 'Onion', 'Tomato', 'Yogurt', 'Ginger', 'Garlic', 'Garam Masala', 'Turmeric', 'Cumin'],
        ingredientsWithQuantities: [
            { name: 'Chicken', amount: 800, unit: 'g' },
            { name: 'Rice', amount: 500, unit: 'g' },
            { name: 'Onion', amount: 3, unit: 'large' },
            { name: 'Tomato', amount: 2, unit: '' },
            { name: 'Yogurt', amount: 1, unit: 'cup' },
            { name: 'Ginger', amount: 2, unit: 'inch' },
            { name: 'Garlic', amount: 6, unit: 'cloves' },
            { name: 'Garam Masala', amount: 2, unit: 'tsp' },
            { name: 'Turmeric', amount: 1, unit: 'tsp' },
            { name: 'Cumin', amount: 1, unit: 'tsp' }
        ],
        instructions: [
            'Marinate chicken with yogurt and spices for 30 minutes',
            'Cook rice until 70% done, drain and set aside',
            'Fry sliced onions until golden brown',
            'In a pot, layer marinated chicken, then rice, then fried onions',
            'Cover and cook on low heat for 25 minutes, then let it rest for 5 minutes',
            'Mix gently and serve hot with raita'
        ],
        utensils: ['Heavy base pot', 'Rice cooker', 'Deep fryer'],
        nutrition: { calories: 520, protein: 32, carbs: 58, fat: 18 }
    },
    {
        id: 'rec-6',
        title: 'Margherita Pizza',
        image: 'https://images.unsplash.com/photo-1588988949118-c86ba9c9c225?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaXp6YSUyMG1hcmdoZXJpdGElMjBmb29kfGVufDF8fHx8MTc3MTUyMzEyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
        cookingTime: 30,
        prepTime: 15,
        bakingTime: 15,
        restingTime: 60,
        difficulty: 'Medium',
        servings: 2,
        type: 'veg',
        mealType: ['dinner', 'snack'],
        ingredients: ['Wheat Flour', 'Tomato', 'Cheese', 'Garlic', 'Butter'],
        ingredientsWithQuantities: [
            { name: 'Wheat Flour', amount: 300, unit: 'g' },
            { name: 'Tomato', amount: 2, unit: '' },
            { name: 'Cheese', amount: 150, unit: 'g' },
            { name: 'Garlic', amount: 1, unit: 'tsp' },
            { name: 'Butter', amount: 1, unit: 'tbsp' }
        ],
        instructions: [
            'Prepare pizza dough and let it rise for 1 hour',
            'Roll out dough into a circle and spread tomato sauce evenly',
            'Add mozzarella cheese generously',
            'Drizzle with garlic butter',
            'Bake at 450°F for 12-15 minutes',
            'Slice and serve hot'
        ],
        utensils: ['Oven', 'Pizza cutter', 'Rolling pin'],
        nutrition: { calories: 380, protein: 16, carbs: 45, fat: 16 }
    },



    {
        id: 'rec-10',
        title: 'Classic Burger',
        image: 'https://img.freepik.com/premium-photo/thai-curry-burger-with-peanut-sauce-pickled-veggie_1169880-24671.jpg',
        cookingTime: 20,
        prepTime: 10,
        bakingTime: 10,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 1,
        type: 'non-veg',
        mealType: ['lunch', 'dinner'],
        ingredients: ['Beef', 'Wheat Flour', 'Cheese', 'Tomato', 'Onion', 'Garlic'],
        ingredientsWithQuantities: [
            { name: 'Beef', amount: 200, unit: 'g' },
            { name: 'Buns', amount: 1, unit: '' },
            { name: 'Cheese', amount: 1, unit: 'slice' },
            { name: 'Tomato', amount: 1, unit: 'slice' },
            { name: 'Onion', amount: 1, unit: 'slice' },
            { name: 'Garlic', amount: 0.5, unit: 'tsp' }
        ],
        instructions: [
            'Form beef into patties and season well',
            'Grill patties for 4 minutes per side',
            'Toast burger buns lightly and add cheese on patty in last minute',
            'Assemble: bun, patty, tomato, onion',
            'Add your favorite sauce',
            'Serve with fries'
        ],
        utensils: ['Griddle', 'Spatula'],
        nutrition: { calories: 580, protein: 32, carbs: 42, fat: 30 }
    },

    {
        id: 'rec-12',
        title: 'Paneer Tikka',
        image: 'https://images.unsplash.com/photo-1666001120694-3ebe8fd207be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYW5lZXIlMjB0aWtrYSUyMGluZGlhbnxlbnwxfHx8fDE3NzE1MTczMTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
        cookingTime: 30,
        prepTime: 70,
        bakingTime: 20,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 2,
        type: 'veg',
        mealType: ['snack', 'dinner'],
        ingredients: ['Paneer', 'Yogurt', 'Bell Pepper', 'Onion', 'Ginger', 'Garlic', 'Garam Masala', 'Red Chili', 'Lemon'],
        ingredientsWithQuantities: [
            { name: 'Paneer', amount: 300, unit: 'g' },
            { name: 'Yogurt', amount: 0.5, unit: 'cup' },
            { name: 'Bell Pepper', amount: 1, unit: '' },
            { name: 'Onion', amount: 1, unit: '' },
            { name: 'Ginger', amount: 1, unit: 'tsp' },
            { name: 'Garlic', amount: 1, unit: 'tsp' },
            { name: 'Garam Masala', amount: 1, unit: 'tsp' },
            { name: 'Red Chili', amount: 1, unit: 'tsp' },
            { name: 'Lemon', amount: 0.5, unit: '' }
        ],
        instructions: [
            'Cut paneer and vegetables into cubes',
            'Mix yogurt with all spices, ginger, garlic, and lemon juice',
            'Marinate paneer and vegetables for 1 hour',
            'Thread onto skewers alternating paneer and vegetables',
            'Grill or bake at 400°F for 15-20 minutes, turning occasionally',
            'Serve hot with mint chutney'
        ],
        utensils: ['Skewers', 'Baking tray', 'Mixing bowl'],
        nutrition: { calories: 290, protein: 16, carbs: 12, fat: 20 }
    },
    {
        id: 'rec-13',
        title: 'Idli & Sambar',
        image: 'https://static.vecteezy.com/system/resources/thumbnails/015/933/612/small_2x/idly-sambar-or-idli-with-sambhar-and-green-red-chutney-popular-south-indian-breakfast-free-photo.jpg',
        cookingTime: 40,
        prepTime: 480,
        bakingTime: 25,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'veg',
        mealType: ['breakfast'],
        ingredients: ['Rice', 'Lentils', 'Tomato', 'Onion', 'Curry Leaves', 'Mustard Seeds', 'Tamarind'],
        ingredientsWithQuantities: [
            { name: 'Rice', amount: 2, unit: 'cups' },
            { name: 'Lentils', amount: 1, unit: 'cup' },
            { name: 'Tomato', amount: 1, unit: '' },
            { name: 'Onion', amount: 1, unit: '' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Tamarind', amount: 30, unit: 'g' }
        ],
        instructions: [
            'Soak rice and lentils separately for 4-6 hours',
            'Grind into a smooth batter and ferment overnight',
            'Steam batter in idli molds for 10-12 minutes',
            'Cook lentils with vegetables and tamarind pulp for sambar',
            'Prepare tempering with mustard seeds and curry leaves, add to sambar',
            'Serve hot idlis with sambar and coconut chutney'
        ],
        utensils: ['Idli steamer', 'Wet grinder', 'Pot'],
        nutrition: { calories: 250, protein: 8, carbs: 45, fat: 4 }
    },
    {
        id: 'rec-14',
        title: 'Bisi Bele Bath',
        image: 'https://sagafoods.in/wp-content/uploads/2022/02/Bisi_Bele_Bath_Bisibelebath-scaled.jpeg',
        cookingTime: 50,
        prepTime: 15,
        bakingTime: 35,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 2,
        type: 'veg',
        mealType: ['lunch'],
        ingredients: ['Rice', 'Lentils', 'Carrot', 'Potato', 'Bell Pepper', 'Curry Leaves', 'Coconut', 'Tamarind'],
        ingredientsWithQuantities: [
            { name: 'Rice', amount: 1, unit: 'cup' },
            { name: 'Lentils', amount: 0.5, unit: 'cup' },
            { name: 'Carrot', amount: 1, unit: '' },
            { name: 'Potato', amount: 1, unit: '' },
            { name: 'Bell Pepper', amount: 1, unit: '' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' },
            { name: 'Coconut', amount: 2, unit: 'tbsp' },
            { name: 'Tamarind', amount: 15, unit: 'g' }
        ],
        instructions: [
            'Cook rice and lentils together until soft',
            'Sauté vegetables with bisi bele bath spice powder',
            'Add tamarind pulp and salt',
            'Mix cooked rice and lentils with vegetables',
            'Add grated coconut and simmer for 5 minutes',
            'Top with ghee and serve hot with papadum'
        ],
        utensils: ['Pressure cooker', 'Sauté pan'],
        nutrition: { calories: 420, protein: 12, carbs: 65, fat: 14 }
    },
    {
        id: 'rec-15',
        title: 'Chicken Chettinad',
        image: 'https://tse2.mm.bing.net/th/id/OIP.dCPAP6lHGYJuJw714pHogAHaHa?w=1200&h=1200&rs=1&pid=ImgDetMain&o=7&rm=3',
        cookingTime: 55,
        prepTime: 20,
        bakingTime: 35,
        restingTime: 0,
        difficulty: 'Hard',
        servings: 3,
        type: 'non-veg',
        mealType: ['lunch', 'dinner'],
        ingredients: ['Chicken', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Star Anise', 'Curry Leaves', 'Coconut'],
        ingredientsWithQuantities: [
            { name: 'Chicken', amount: 600, unit: 'g' },
            { name: 'Onion', amount: 2, unit: '' },
            { name: 'Tomato', amount: 1, unit: '' },
            { name: 'Ginger', amount: 1, unit: 'tsp' },
            { name: 'Garlic', amount: 1, unit: 'tsp' },
            { name: 'Star Anise', amount: 2, unit: '' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' },
            { name: 'Coconut', amount: 0.5, unit: 'cup' }
        ],
        instructions: [
            'Roast dry spices and coconut, then grind into a paste',
            'Heat oil and sauté onions, curry leaves, and ginger-garlic paste',
            'Add tomatoes and cook until soft',
            'Add chicken pieces and the prepared spice paste',
            'Cook until chicken is tender and gravy thickens',
            'Garnish with fresh coriander and serve hot with paratha or rice'
        ],
        utensils: ['Spice grinder', 'Deep pot'],
        nutrition: { calories: 480, protein: 35, carbs: 12, fat: 32 }
    },
    {
        id: 'rec-16',
        title: 'Ven Pongal',
        image: 'https://www.tasteatlas.com/images/dishes/fdf3d872feb744799312e5fb37b705a0.jpg?mw=1300',
        cookingTime: 30,
        prepTime: 10,
        bakingTime: 20,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 4,
        type: 'veg',
        mealType: ['breakfast'],
        ingredients: ['Rice', 'Lentils', 'Butter', 'Ginger', 'Cumin', 'Curry Leaves', 'Mustard Seeds'],
        ingredientsWithQuantities: [
            { name: 'Rice', amount: 1, unit: 'cup' },
            { name: 'Lentils', amount: 0.5, unit: 'cup' },
            { name: 'Butter', amount: 3, unit: 'tbsp' },
            { name: 'Ginger', amount: 1, unit: 'inch' },
            { name: 'Cumin', amount: 1, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' },
            { name: 'Mustard Seeds', amount: 0.5, unit: 'tsp' }
        ],
        instructions: [
            'Dry roast moong dal until golden',
            'Wash and cook rice and dal together in a pressure cooker until soft and mushy',
            'Heat butter, splutter mustard seeds, cumin, curry leaves, and ginger',
            'Add cashews and fry until golden',
            'Pour the tempering over the pongal, mix well, and season with salt and pepper',
            'Serve piping hot with coconut chutney and sambar'
        ],
        utensils: ['Pressure cooker', 'Tadka pan', 'Ladle'],
        nutrition: { calories: 310, protein: 10, carbs: 48, fat: 10 }
    },
    {
        id: 'rec-17',
        title: 'Crispy Dosa & Coconut Chutney',
        image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh5hk1j_3CQz4YG1HmkSWuN4m1dDtqF3e3Ekh9XO1sRAMVgt1KW4NnQ8syObn8SsjyDHnpsgNOxbRxvXpA4gTZSoDrhMelfIulPJUI2r9GlSoiC23R3KWYWRqWC8waSBpl4jCIP-yeJ_QjQipE4-qgZcgcTvKbAR5apFPsaHRt05g72GaQ8dv_BYg/s644/Vellulli%20Karam%20Dosa%20(2).JPG',
        cookingTime: 30,
        prepTime: 480,
        bakingTime: 5,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'veg',
        mealType: ['breakfast', 'dinner'],
        ingredients: ['Rice', 'Lentils', 'Coconut', 'Curry Leaves', 'Mustard Seeds', 'Ginger'],
        ingredientsWithQuantities: [
            { name: 'Rice', amount: 3, unit: 'cups' },
            { name: 'Lentils', amount: 1, unit: 'cup' },
            { name: 'Coconut', amount: 1, unit: 'cup' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Ginger', amount: 0.5, unit: 'inch' }
        ],
        instructions: [
            'Soak rice and lentils for 6-8 hours, grind into a batter, and ferment overnight',
            'For chutney: blend coconut, green chili, and ginger into a paste',
            'Prepare tempering with mustard seeds and curry leaves for the chutney',
            'Heat a flat griddle until very hot, pour a ladle of batter, and spread thinly',
            'Drizzle oil on edges and cook until golden and crispy',
            'Serve hot with coconut chutney and sambar'
        ],
        utensils: ['Wet grinder or blender', 'Flat tawa/griddle', 'Ladle', 'Spatula'],
        nutrition: { calories: 220, protein: 7, carbs: 40, fat: 5 }
    },
    {
        id: 'rec-18',
        title: 'Rava Upma',
        image: 'https://rakskitchen.net/wp-content/uploads/2013/02/upma-recipe-feat.jpg',
        cookingTime: 20,
        prepTime: 5,
        bakingTime: 15,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 2,
        type: 'veg',
        mealType: ['breakfast'],
        ingredients: ['Onion', 'Tomato', 'Carrot', 'Spinach', 'Mustard Seeds', 'Curry Leaves', 'Ginger', 'Butter', 'Cumin'],
        ingredientsWithQuantities: [
            { name: 'Onion', amount: 1, unit: 'medium' },
            { name: 'Tomato', amount: 1, unit: '' },
            { name: 'Carrot', amount: 1, unit: 'small' },
            { name: 'Spinach', amount: 50, unit: 'g' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' },
            { name: 'Ginger', amount: 0.5, unit: 'inch' },
            { name: 'Butter', amount: 2, unit: 'tbsp' },
            { name: 'Cumin', amount: 0.5, unit: 'tsp' }
        ],
        instructions: [
            'Dry roast sooji on low heat until fragrant and set aside',
            'Heat butter, splutter mustard seeds, cumin, curry leaves, green chili, and ginger',
            'Add chopped onion, tomatoes, and diced vegetables, cook until soft',
            'Add boiling water and salt, bring to a boil',
            'Add roasted rava slowly while stirring continuously to avoid lumps',
            'Cover and cook on low heat for 5 minutes, serve hot with coconut chutney'
        ],
        utensils: ['Heavy-bottomed pan', 'Wooden spoon', 'Lid'],
        nutrition: { calories: 265, protein: 6, carbs: 44, fat: 8 }
    },
    {
        id: 'rec-19',
        title: 'Medu Vada',
        image: 'https://myfoodstory.com/wp-content/uploads/2022/09/Medu-Vada-2-768x1152.jpg',
        cookingTime: 30,
        prepTime: 240,
        bakingTime: 20,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'veg',
        mealType: ['breakfast', 'snack'],
        ingredients: ['Lentils', 'Onion', 'Ginger', 'Cumin', 'Curry Leaves', 'Red Chili'],
        ingredientsWithQuantities: [
            { name: 'Lentils', amount: 2, unit: 'cups' },
            { name: 'Onion', amount: 1, unit: 'medium' },
            { name: 'Ginger', amount: 1, unit: 'inch' },
            { name: 'Cumin', amount: 1, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' },
            { name: 'Red Chili', amount: 2, unit: '' }
        ],
        instructions: [
            'Soak urad dal for 3-4 hours, drain, and grind into a thick, fluffy batter',
            'Add finely chopped onion, ginger, curry leaves, cumin, and salt',
            'Mix vigorously to incorporate air, heat oil in a deep pan to 180°C',
            'Shape batter into a donut shape with wet hands',
            'Slide into hot oil and fry until golden brown, flipping once',
            'Drain on paper towels and serve hot with chutney and sambar'
        ],
        utensils: ['Wet grinder or blender', 'Deep frying kadai', 'Slotted spoon', 'Paper towels'],
        nutrition: { calories: 195, protein: 9, carbs: 28, fat: 6 }
    },
    {
        id: 'rec-20',
        title: 'Puttu & Kadala Curry',
        image: 'https://images.slurrp.com/prod/articles/2p9newjj1z8.webp',
        cookingTime: 35,
        prepTime: 15,
        bakingTime: 20,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 3,
        type: 'veg',
        mealType: ['breakfast'],
        ingredients: ['Rice', 'Coconut', 'Lentils', 'Onion', 'Tomato', 'Turmeric', 'Mustard Seeds', 'Curry Leaves', 'Coriander'],
        ingredientsWithQuantities: [
            { name: 'Rice', amount: 2, unit: 'cups' },
            { name: 'Coconut', amount: 1, unit: 'cup' },
            { name: 'Lentils', amount: 1.5, unit: 'cups' },
            { name: 'Onion', amount: 1, unit: 'large' },
            { name: 'Tomato', amount: 2, unit: '' },
            { name: 'Turmeric', amount: 0.5, unit: 'tsp' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' },
            { name: 'Coriander', amount: 1, unit: 'tsp' }
        ],
        instructions: [
            'Soak black chickpeas overnight and pressure cook until soft',
            'Mix rice flour with grated coconut and salt, steam in slightly moist layers',
            'For curry: heat oil, splutter mustard seeds and curry leaves',
            'Sauté onions, ginger-garlic paste, tomatoes, and spices until thick',
            'Add cooked chickpeas and coconut milk, simmer for 10 minutes',
            'Garnish with coriander and serve steamed puttu with the rich kadala curry'
        ],
        utensils: ['Pressure cooker', 'Puttu maker/steamer', 'Deep pan'],
        nutrition: { calories: 355, protein: 13, carbs: 60, fat: 9 }
    },
    {
        id: 'rec-21',
        title: 'Chettinad Fish Curry',
        image: 'https://myfoodstory.com/wp-content/uploads/2022/06/Raw-Mango-Fish-Curry-1-720x1080.jpg',
        cookingTime: 40,
        prepTime: 20,
        bakingTime: 0,
        restingTime: 30,
        difficulty: 'Hard',
        servings: 4,
        type: 'non-veg',
        mealType: ['lunch'],
        ingredients: ['Fish', 'Tomato', 'Onion', 'Tamarind', 'Garlic', 'Curry Leaves', 'Mustard Seeds', 'Coconut'],
        ingredientsWithQuantities: [
            { name: 'Fish', amount: 500, unit: 'g' },
            { name: 'Onion', amount: 2, unit: 'medium' },
            { name: 'Tomato', amount: 2, unit: 'medium' },
            { name: 'Tamarind', amount: 30, unit: 'g' },
            { name: 'Garlic', amount: 6, unit: 'cloves' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' },
            { name: 'Coconut', amount: 0.5, unit: 'cup' }
        ],
        instructions: [
            'Extract tamarind juice and grind roasted spices and coconut into a paste',
            'Heat sesame oil, splutter mustard seeds, fenugreek, curry leaves, and garlic',
            'Sauté onions and tomatoes until mushy',
            'Pour in tamarind extract, ground masala, and simmer until oil separates',
            'Gently slide in washed fish pieces and cook covered for 5-7 minutes',
            'Serve hot with steamed rice or idli'
        ],
        utensils: ['Clay pot or deep pan', 'Mixer grinder', 'Ladle'],
        nutrition: { calories: 350, protein: 28, carbs: 12, fat: 22 }
    },
    {
        id: 'rec-22',
        title: 'Ambur Mutton Biryani',
        image: 'https://www.scrumptiously.com/wp-content/uploads/2023/04/MuttonBiryani.webp',
        cookingTime: 60,
        prepTime: 30,
        bakingTime: 0,
        restingTime: 20,
        difficulty: 'Hard',
        servings: 5,
        type: 'non-veg',
        mealType: ['lunch'],
        ingredients: ['Mutton', 'Rice', 'Tomato', 'Onion', 'Garlic', 'Ginger', 'Yogurt', 'Red Chili'],
        ingredientsWithQuantities: [
            { name: 'Mutton', amount: 500, unit: 'g' },
            { name: 'Seeraga Samba Rice', amount: 2.5, unit: 'cups' },
            { name: 'Onion', amount: 4, unit: 'medium' },
            { name: 'Tomato', amount: 3, unit: 'medium' },
            { name: 'Ginger', amount: 2, unit: 'tbsp' },
            { name: 'Garlic', amount: 2, unit: 'tbsp' },
            { name: 'Yogurt', amount: 0.5, unit: 'cup' },
            { name: 'Red Chili Paste', amount: 2, unit: 'tbsp' }
        ],
        instructions: [
            'Soak rice and pressure cook mutton with ginger-garlic paste until tender',
            'Heat oil/ghee, sauté whole spices, onions, and freshly ground ginger-garlic paste',
            'Add red chili paste, chopped tomatoes, yogurt, herbs, and cook until oil separates',
            'Add cooked mutton, stock, and adjust water for the rice',
            'Bring to a boil, add drained rice, and check for salt',
            'Cover and cook on low heat for 15 minutes, rest, and serve with onion raita'
        ],
        utensils: ['Heavy bottom wide pan with tight lid', 'Pressure cooker'],
        nutrition: { calories: 650, protein: 35, carbs: 65, fat: 28 }
    },
    {
        id: 'rec-23',
        title: 'Nattu Kozhi Kulambu',
        image: 'https://www.yummytummyaarthi.com/wp-content/uploads/2018/06/IMG_4659-720x480.jpg',
        cookingTime: 50,
        prepTime: 15,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'non-veg',
        mealType: ['lunch'],
        ingredients: ['Chicken', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Coconut', 'Curry Leaves', 'Turmeric'],
        ingredientsWithQuantities: [
            { name: 'Country Chicken (Bone-in)', amount: 750, unit: 'g' },
            { name: 'Small Onions (Shallots)', amount: 1.5, unit: 'cups' },
            { name: 'Tomato', amount: 2, unit: 'medium' },
            { name: 'Ginger', amount: 1, unit: 'inch' },
            { name: 'Garlic', amount: 6, unit: 'cloves' },
            { name: 'Coconut', amount: 0.5, unit: 'cup' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' },
            { name: 'Turmeric', amount: 1, unit: 'tsp' }
        ],
        instructions: [
            'Dry roast and powder spices, and grind coconut with shallots into a paste',
            'Heat sesame oil, splutter mustard seeds, curry leaves, and sauté shallots',
            'Add ginger, garlic, and tomatoes, cook until mushy',
            'Add chicken, turmeric, salt, and spice powder, roast for 5-8 minutes',
            'Add water and pressure cook for 4-5 whistles until chicken is tender',
            'Add coconut paste, simmer for 5 minutes, and serve hot'
        ],
        utensils: ['Pressure cooker', 'Mixer grinder', 'Ladle'],
        nutrition: { calories: 420, protein: 40, carbs: 14, fat: 24 }
    },
    {
        id: 'rec-24',
        title: 'Pallipalayam Chicken',
        image: 'https://www.onmanorama.com/content/dam/mm/en/food/recipe/images/2022/7/26/chicken-pallipalayam.jpg.transform/845x440/image.jpg',
        cookingTime: 35,
        prepTime: 15,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 3,
        type: 'non-veg',
        mealType: ['lunch', 'dinner'],
        ingredients: ['Chicken', 'Onion', 'Red Chili', 'Garlic', 'Coconut', 'Turmeric', 'Curry Leaves'],
        ingredientsWithQuantities: [
            { name: 'Chicken (Bite-sized)', amount: 500, unit: 'g' },
            { name: 'Shallots (Small Onions)', amount: 1, unit: 'cup' },
            { name: 'Dry Red Chilies (Deseeded)', amount: 15, unit: '' },
            { name: 'Garlic', amount: 8, unit: 'cloves' },
            { name: 'Coconut (Bite-sized pieces)', amount: 0.25, unit: 'cup' },
            { name: 'Turmeric', amount: 0.5, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' }
        ],
        instructions: [
            'Grate or crush garlic cloves roughly',
            'Heat oil, splutter mustard seeds, and sauté shallots until translucent',
            'Add crushed garlic, curry leaves, and deseeded dry red chilies',
            'Add chicken and turmeric, fry until chicken changes color, and cook covered',
            'Once chicken is tender, add thinly sliced fresh coconut pieces',
            'Roast uncovered until chicken is completely dry and serve hot'
        ],
        utensils: ['Heavy bottom wok (Kadai)', 'Spatula'],
        nutrition: { calories: 380, protein: 35, carbs: 10, fat: 22 }
    },
    {
        id: 'rec-25',
        title: 'Vatha Kuzhambu',
        image: 'https://farm8.staticflickr.com/7435/9376007129_efc89ed9bd_c.jpg',
        cookingTime: 30,
        prepTime: 10,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'veg',
        mealType: ['lunch'],
        ingredients: ['Tamarind', 'Onion', 'Garlic', 'Mustard Seeds', 'Curry Leaves', 'Tomato'],
        ingredientsWithQuantities: [
            { name: 'Tamarind', amount: 40, unit: 'g' },
            { name: 'Sundakkai Vathal (Dried Turkey Berry)', amount: 2, unit: 'tbsp' },
            { name: 'Shallots', amount: 15, unit: 'whole' },
            { name: 'Garlic', amount: 10, unit: 'cloves' },
            { name: 'Sambar Powder', amount: 2, unit: 'tbsp' },
            { name: 'Jaggery', amount: 1, unit: 'tsp' },
            { name: 'Sesame Oil', amount: 3, unit: 'tbsp' }
        ],
        instructions: [
            'Extract tamarind juice and fry dried berries in sesame oil until crisp',
            'In the same pan, temper mustard seeds, fenugreek, curry leaves, garlic, and shallots',
            'Add chopped tomato (optional), sambar powder, and turmeric, mixing quickly',
            'Pour in tamarind extract, salt, and boil until the gravy thickens',
            'Add the fried berries and jaggery, simulate until oil floats',
            'Serve with steamed rice and poriyal'
        ],
        utensils: ['Pan', 'Ladle'],
        nutrition: { calories: 210, protein: 4, carbs: 25, fat: 12 }
    },
    {
        id: 'rec-26',
        title: 'Thayir Sadam (Curd Rice)',
        image: 'https://healthyindianrecipes.com/wp-content/uploads/2025/10/curd-rice-dish-191025.jpg',
        cookingTime: 15,
        prepTime: 20,
        bakingTime: 0,
        restingTime: 30,
        difficulty: 'Easy',
        servings: 2,
        type: 'veg',
        mealType: ['lunch'],
        ingredients: ['Rice', 'Yogurt', 'Milk', 'Mustard Seeds', 'Curry Leaves', 'Ginger', 'Carrot'],
        ingredientsWithQuantities: [
            { name: 'Rice', amount: 1, unit: 'cup' },
            { name: 'Yogurt (Curd)', amount: 1.5, unit: 'cups' },
            { name: 'Milk', amount: 0.5, unit: 'cup' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Urad Dal (Split Black Gram)', amount: 1, unit: 'tsp' },
            { name: 'Ginger', amount: 1, unit: 'tsp' },
            { name: 'Green Chilies', amount: 1, unit: '' },
            { name: 'Pomegranate Seeds or Grated Carrot', amount: 2, unit: 'tbsp' }
        ],
        instructions: [
            'Pressure cook rice until soft and mushy, mash well while hot',
            'Let rice cool, then mix with yogurt, milk, and salt until creamy',
            'For tempering: heat oil, splutter mustard seeds and urad dal until golden',
            'Add finely chopped ginger, green chilies, and curry leaves, sauté briefly',
            'Pour tempering over curd rice and mix gently',
            'Garnish with pomegranate or carrots, serve chilled with pickle'
        ],
        utensils: ['Pressure cooker', 'Tadka pan', 'Potato masher'],
        nutrition: { calories: 290, protein: 10, carbs: 54, fat: 5 }
    },
    {
        id: 'rec-27',
        title: 'Idiyappam & Vegetable Stew',
        image: 'https://gramiyum.in/wp-content/uploads/2024/04/Idiyappam-with-stew-800x530.jpg',
        cookingTime: 30,
        prepTime: 20,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'veg',
        mealType: ['breakfast', 'dinner'],
        ingredients: ['Rice Flour', 'Coconut Milk', 'Carrot', 'Potato', 'Ginger', 'Green Chilies', 'Curry Leaves', 'Cinnamon'],
        ingredientsWithQuantities: [
            { name: 'Roasted Rice Flour', amount: 2, unit: 'cups' },
            { name: 'Thick Coconut Milk', amount: 1, unit: 'cup' },
            { name: 'Carrot', amount: 1, unit: 'medium' },
            { name: 'Potato', amount: 1, unit: 'medium' },
            { name: 'Ginger', amount: 1, unit: 'inch' },
            { name: 'Green Chilies', amount: 2, unit: '' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' },
            { name: 'Cinnamon', amount: 1, unit: 'stick' }
        ],
        instructions: [
            'Mix boiling water into rice flour to form a smooth dough',
            'Squeeze dough into steamer plates and steam for 8-10 minutes',
            'For the stew: sauté whole spices, onions, ginger, green chilies, and curry leaves',
            'Add carrots, potatoes, peas, and thin coconut milk, cook until tender',
            'Add thick coconut milk on low heat without boiling',
            'Serve hot stringy idiyappam with the creamy vegetable stew'
        ],
        utensils: ['Idiyappam Press', 'Steamer', 'Pan'],
        nutrition: { calories: 340, protein: 6, carbs: 62, fat: 12 }
    },
    {
        id: 'rec-28',
        title: 'Kuzhi Paniyaram',
        image: 'https://tse4.mm.bing.net/th/id/OIP.KhRDXyblPICx47_0iVMCSQHaHa?w=751&h=752&rs=1&pid=ImgDetMain&o=7&rm=3',
        cookingTime: 20,
        prepTime: 15,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 3,
        type: 'veg',
        mealType: ['breakfast', 'dinner', 'snack'],
        ingredients: ['Idli Batter', 'Onion', 'Curry Leaves', 'Mustard Seeds', 'Green Chilies', 'Coriander'],
        ingredientsWithQuantities: [
            { name: 'Leftover Idli/Dosa Batter', amount: 2, unit: 'cups' },
            { name: 'Onion', amount: 1, unit: 'large' },
            { name: 'Mustard Seeds', amount: 1, unit: 'tsp' },
            { name: 'Chana Dal', amount: 1, unit: 'tsp' },
            { name: 'Green Chilies', amount: 2, unit: '' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' },
            { name: 'Coriander Leaves', amount: 2, unit: 'tbsp' }
        ],
        instructions: [
            'Heat oil, splutter mustard seeds and chana dal',
            'Sauté chopped onions, green chilies, and curry leaves until golden',
            'Mix tempered ingredients and coriander leaves into leftover idli batter',
            'Heat a paniyaram pan, add oil, and fill each cavity 3/4th with batter',
            'Cook covered until the bottom is crispy, then flip and cook the other side',
            'Serve hot with spicy tomato-garlic chutney'
        ],
        utensils: ['Paniyaram Pan', 'Tadka pan'],
        nutrition: { calories: 250, protein: 8, carbs: 42, fat: 6 }
    },
    {
        id: 'rec-29',
        title: 'Adai & Avial',
        image: 'https://www.yummytummyaarthi.com/wp-content/uploads/2016/02/1-22.jpg',
        cookingTime: 30,
        prepTime: 180,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 4,
        type: 'veg',
        mealType: ['breakfast', 'dinner'],
        ingredients: ['Rice', 'Lentils', 'Coconut', 'Carrot', 'Yogurt', 'Cumin', 'Red Chili'],
        ingredientsWithQuantities: [
            { name: 'Mixed Lentils (Chana, Toor, Urad dal)', amount: 1, unit: 'cup' },
            { name: 'Rice', amount: 1, unit: 'cup' },
            { name: 'Mixed Vegetables for Avial', amount: 3, unit: 'cups' },
            { name: 'Grated Coconut', amount: 1, unit: 'cup' },
            { name: 'Dried Red Chilies', amount: 4, unit: '' },
            { name: 'Yogurt', amount: 0.5, unit: 'cup' },
            { name: 'Cumin', amount: 1, unit: 'tsp' }
        ],
        instructions: [
            'Soak rice, mixed lentils, and red chilies, then grind into a thick batter',
            'For avial: steam mixed vegetables with turmeric until just cooked',
            'Grind coconut, chilies, cumin, add to vegetables, and stir in yogurt and coconut oil',
            'Heat a griddle, spread adai batter thicker than a dosa, and drizzle with oil/ghee',
            'Cook both sides of adai until deep golden and crispy',
            'Serve hot adai with avial and jaggery'
        ],
        utensils: ['Grinder', 'Flat tawa', 'Cooking pot'],
        nutrition: { calories: 410, protein: 18, carbs: 55, fat: 12 }
    },
    {
        id: 'rec-30',
        title: 'Veg Kothu Parotta',
        image: 'https://cdn.shopify.com/s/files/1/0274/1944/3269/products/Vegetable-Kothu-Paratha-currybliss_1800x1800.jpg?v=1590071633',
        cookingTime: 20,
        prepTime: 10,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 2,
        type: 'veg',
        mealType: ['dinner'],
        ingredients: ['Parotta', 'Onion', 'Tomato', 'Bell Pepper', 'Curry Leaves', 'Fennel Seeds', 'Garam Masala'],
        ingredientsWithQuantities: [
            { name: 'Leftover Flaky Parottas', amount: 3, unit: '' },
            { name: 'Onion', amount: 2, unit: 'medium' },
            { name: 'Tomato', amount: 1, unit: 'medium' },
            { name: 'Mixed Veggies (Carrot, Cabbage, Capsicum)', amount: 1, unit: 'cup' },
            { name: 'Veg Salna (Curry sauce)', amount: 0.5, unit: 'cup' },
            { name: 'Fennel Seeds', amount: 1, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 2, unit: 'sprigs' }
        ],
        instructions: [
            'Tear cooled parottas into bite-sized pieces',
            'Heat oil in a wide pan, temper fennel seeds, curry leaves, and sauté onions',
            'Add ginger-garlic paste, tomatoes, mixed vegetables, and spices, cook until tender',
            'Pour in veg salna (curry sauce) and let it bubble, then add parotta pieces',
            'Vigorously mince and stir-fry the mixture on high heat for a few minutes',
            'Serve hot with onion raita and an extra side of salna'
        ],
        utensils: ['Iron griddle (Tawa) or wide wok', 'Two flat metal spatulas'],
        nutrition: { calories: 550, protein: 12, carbs: 75, fat: 22 }
    },
    {
        id: 'rec-31',
        title: 'Madurai Kari Dosa',
        image: 'https://www.chennaionline.com/wp-content/uploads/2019/06/madurai-kari-dosa-recipe.jpg',
        cookingTime: 25,
        prepTime: 15,
        bakingTime: 0,
        restingTime: 0,
        difficulty: 'Hard',
        servings: 2,
        type: 'non-veg',
        mealType: ['dinner'],
        ingredients: ['Dosa Batter', 'Mutton', 'Egg', 'Onion', 'Ginger', 'Pepper', 'Garam Masala'],
        ingredientsWithQuantities: [
            { name: 'Thick Dosa Batter', amount: 2, unit: 'cups' },
            { name: 'Mutton Keema (Minced Meat)', amount: 250, unit: 'g' },
            { name: 'Eggs', amount: 2, unit: '' },
            { name: 'Onion', amount: 1, unit: 'large' },
            { name: 'Ginger-Garlic Paste', amount: 1, unit: 'tbsp' },
            { name: 'Pepper Powder', amount: 1, unit: 'tsp' },
            { name: 'Coriander Leaves', amount: 2, unit: 'tbsp' }
        ],
        instructions: [
            'Prepare mutton keema sukka by sautéing spices, onions, and minced meat until dry',
            'Beat an egg in a small bowl with a pinch of salt and pepper',
            'Spread a thick circle of dosa batter on a hot cast iron tawa and let cook slightly',
            'Pour the beaten egg evenly over the dosa, then spoon the cooked keema on top',
            'Carefully flip and cook the meat-egg side on medium heat until charred',
            'Flip back, garnish with fresh coriander, and serve hot'
        ],
        utensils: ['Thick cast iron tawa', 'Spatula'],
        nutrition: { calories: 480, protein: 34, carbs: 42, fat: 18 }
    },
    {
        id: 'rec-32',
        title: 'Appam & Chicken Stew',
        image: 'https://as1.ftcdn.net/v2/jpg/05/69/37/78/1000_F_569377886_tNOWGIbK1zewK9xAP1j2KHQUg21MdnFr.jpg',
        cookingTime: 40,
        prepTime: 30,
        bakingTime: 0,
        restingTime: 120,
        difficulty: 'Medium',
        servings: 4,
        type: 'non-veg',
        mealType: ['dinner'],
        ingredients: ['Rice', 'Coconut', 'Chicken', 'Potato', 'Cardamom', 'Cinnamon', 'Green Chilies', 'Coconut Milk'],
        ingredientsWithQuantities: [
            { name: 'Raw Rice', amount: 2, unit: 'cups' },
            { name: 'Grated Coconut', amount: 1, unit: 'cup' },
            { name: 'Chicken (Bone-in)', amount: 500, unit: 'g' },
            { name: 'Thick & Thin Coconut Milk', amount: 2, unit: 'cups' },
            { name: 'Potato', amount: 1, unit: 'medium' },
            { name: 'Whole Spices (Cardamom, Cloves, Cinnamon)', amount: 1, unit: 'tbsp' },
            { name: 'Green Chilies', amount: 3, unit: '' }
        ],
        instructions: [
            'For Appam: Grind soaked rice with grated coconut and yeast, ferment for 8 hours',
            'For the stew: Sauté whole spices, onions, ginger, and green chilies until soft',
            'Add chicken, potatoes, and thin coconut milk, cook until tender',
            'Reduce heat, pour in thick coconut milk without boiling, and turn off heat',
            'Pour appam batter into a hot appachatti, swirl to coat, and cook covered until edges are crispy',
            'Serve hot appam with the mildly spiced, creamy chicken stew'
        ],
        utensils: ['Appachatti (Appam Pan)', 'Deep Cooking Pot', 'Grinder'],
        nutrition: { calories: 520, protein: 32, carbs: 54, fat: 20 }
    },
    {
        id: 'rec-33',
        title: 'Muttai Dosa (Egg Dosa)',
        image: 'https://www.whiskaffair.com/wp-content/uploads/2017/06/DSC4641-1024x684.jpg',
        cookingTime: 15,
        prepTime: 5,
        bakingTime: 10,
        restingTime: 0,
        difficulty: 'Easy',
        servings: 2,
        type: 'non-veg',
        mealType: ['breakfast'],
        ingredients: ['Rice', 'Lentils', 'Egg', 'Onion', 'Green Chili', 'Black Pepper', 'Curry Leaves'],
        ingredientsWithQuantities: [
            { name: 'Dosa Batter', amount: 2, unit: 'cups' },
            { name: 'Eggs', amount: 2, unit: '' },
            { name: 'Onion', amount: 1, unit: 'small' },
            { name: 'Black Pepper', amount: 0.5, unit: 'tsp' },
            { name: 'Curry Leaves', amount: 1, unit: 'sprig' }
        ],
        instructions: [
            'Spread a thin layer of dosa batter on a hot tawa',
            'Crack an egg slightly in a bowl and pour it in the center',
            'Spread the egg evenly over the batter',
            'Sprinkle chopped onion, green chili, and black pepper on top',
            'Drizzle oil on edges and cook until the bottom is crispy and egg is cooked',
            'Fold and serve hot with chutney'
        ],
        utensils: ['Tawa', 'Spatula'],
        nutrition: { calories: 280, protein: 12, carbs: 35, fat: 8 }
    },
    {
        id: 'rec-34',
        title: 'Chicken Keema Paratha',
        image: 'https://www.licious.in/blog/wp-content/uploads/2020/04/shutterstock_83591092.jpg',
        cookingTime: 30,
        prepTime: 15,
        bakingTime: 15,
        restingTime: 0,
        difficulty: 'Medium',
        servings: 2,
        type: 'non-veg',
        mealType: ['breakfast'],
        ingredients: ['Wheat Flour', 'Chicken', 'Onion', 'Ginger', 'Garlic', 'Garam Masala', 'Turmeric'],
        ingredientsWithQuantities: [
            { name: 'Wheat Flour', amount: 1.5, unit: 'cups' },
            { name: 'Minced Chicken', amount: 200, unit: 'g' },
            { name: 'Onion', amount: 1, unit: 'small' },
            { name: 'Garam Masala', amount: 1, unit: 'tsp' }
        ],
        instructions: [
            'Sauté minced chicken with onions and spices until well cooked',
            'Make a smooth dough from wheat flour',
            'Roll dough into small circles and place chicken stuffing in the center',
            'Fold the edges into a ball, sealing the stuffing inside',
            'Roll out again gently into a paratha shape',
            'Cook on a hot tawa with ghee on both sides until golden and serve hot'
        ],
        utensils: ['Tawa', 'Rolling Pin', 'Pan'],
        nutrition: { calories: 350, protein: 22, carbs: 40, fat: 12 }
    }
];
